DELIMITER //
CREATE TRIGGER apts_AI_TRIGGER AFTER INSERT ON APUNTES
FOR EACH ROW
BEGIN
INSERT INTO SALDO SET
	SALDO.CUENTA=NEW.CUENTA,
	SALDO.ANO=YEAR(NEW.FECHA),
	SALDO.MES=MONTH(NEW.FECHA),
	SALDO.DEBE=NEW.DEBE,
	SALDO.HABER=NEW.HABER
ON DUPLICATE KEY UPDATE
	SALDO.DEBE=SALDO.DEBE+NEW.DEBE,
	SALDO.HABER=SALDO.HABER+NEW.HABER;
END;//
DELIMITER ;