DELIMITER //
CREATE TRIGGER apts_AD_TRIGGER AFTER DELETE ON APUNTES
FOR EACH ROW
BEGIN
INSERT INTO SALDO SET
	SALDO.CUENTA=OLD.CUENTA,
	SALDO.ANO=YEAR(OLD.FECHA),
	SALDO.MES=MONTH(OLD.FECHA),
	SALDO.DEBE=OLD.DEBE*(-1),
	SALDO.HABER=OLD.HABER*(-1)
ON DUPLICATE KEY UPDATE
	SALDO.DEBE=SALDO.DEBE+(OLD.DEBE*(-1)),
	SALDO.HABER=SALDO.HABER+(OLD.HABER*(-1));
END;//
DELIMITER ;