DELIMITER //
CREATE TRIGGER apts_AU_TRIGGER AFTER update ON APUNTES
FOR EACH ROW
BEGIN
INSERT INTO SALDO SET
	SALDO.CUENTA=OLD.CUENTA,
	SALDO.ANO=YEAR(OLD.FECHA),
	SALDO.MES=MONTH(OLD.FECHA),
	SALDO.DEBE=OLD.DEBE*(-1),
	SALDO.HABER=OLD.HABER*(-1)
ON DUPLICATE KEY UPDATE
	SALDO.DEBE=SALDO.DEBE+(OLD.DEBE*(-1)),
	SALDO.HABER=SALDO.HABER+(OLD.HABER*(-1));
	
INSERT INTO SALDO SET
SALDO.CUENTA=NEW.CUENTA,
SALDO.ANO=YEAR(NEW.FECHA),
SALDO.MES=MONTH(NEW.FECHA),
SALDO.DEBE=NEW.DEBE,
SALDO.HABER=NEW.HABER
ON DUPLICATE KEY UPDATE
	SALDO.DEBE=SALDO.DEBE+NEW.DEBE,
	SALDO.HABER=SALDO.HABER+NEW.HABER;
END;//
DELIMITER ;